default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "rails") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password123") %>
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>

development:
  <<: *default
  database: invoice_service_development

test:
  <<: *default
  database: invoice_service_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>