default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 5000
  prepared_statements: false

development:
  <<: *default
  database: audit_service_development
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>

test:
  <<: *default
  database: audit_service_test
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>

production:
  <<: *default
  database: audit_service_production
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  prepared_statements: true